/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type Timeline = {
  _type: "timeline";
  items?: Array<{
    title?: string;
    milestones?: Array<
      {
        _key: string;
      } & Milestone
    >;
    _type: "item";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Milestone = {
  _type: "milestone";
  title?: string;
  description?: string;
  points?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageLayout?: "logo" | "cover";
  tags?: Array<string>;
  duration?: Duration;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "nl" | "en";
  title?: string;
  slug?: Slug;
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverVideoUrl?: string;
  duration?: Duration;
  client?: string;
  site?: string;
  tags?: Array<string>;
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Timeline)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Duration = {
  _type: "duration";
  start?: string;
  end?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "nl" | "en";
  title?: string;
  slug?: Slug;
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Timeline)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "nl" | "en";
  menuItems?: ArrayOf<HomeReference | PageReference | ProjectReference>;
  footer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "nl" | "en";
  title?: string;
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  showcaseProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Timeline
  | SanityImageAssetReference
  | Milestone
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Duration
  | Slug
  | Page
  | HomeReference
  | PageReference
  | ProjectReference
  | Settings
  | Home
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: app/[lang]/[slug]/page.tsx
// Variable: slugPageMetadataQuery
// Query: *[      _type == "page" &&      slug.current == $slug &&      language in [$language, "nl"]    ] | order(select(language == $language => 0, 1) asc)[0] {      title,      "overview": pt::text(overview),    }
export type SlugPageMetadataQueryResult = {
  title: string | null;
  overview: string;
} | null;

// Source: app/[lang]/[slug]/page.tsx
// Variable: slugPageQuery
// Query: *[      _type == "page" &&      slug.current == $slug &&      language in [$language, "nl"]    ] | order(select(language == $language => 0, 1) asc)[0] {      _id,      _type,      body,      overview,      title,      "slug": slug.current,    }
export type SlugPageQueryResult = {
  _id: string;
  _type: "page";
  body: Array<
    | ({
        _key: string;
      } & Timeline)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  overview: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  title: string | null;
  slug: string | null;
} | null;

// Source: app/[lang]/layout.tsx
// Variable: layoutMetadataQuery
// Query: {    "settings": *[_type == "settings" && language in [$language, "nl"]]      | order(select(language == $language => 0, 1) asc)[0]{ogImage},    "home": *[_type == "home" && language in [$language, "nl"]]      | order(select(language == $language => 0, 1) asc)[0]{      title,      "overview": pt::text(overview),    }  }
export type LayoutMetadataQueryResult = {
  settings: {
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  home: {
    title: string | null;
    overview: string;
  } | null;
};

// Source: app/[lang]/page.tsx
// Variable: homePageQuery
// Query: {    "home": *[_type == "home" && language in [$language, "nl"]]      | order(select(language == $language => 0, 1) asc)[0]{      _id,      _type,      overview,      title,    },    "pages": *[      _type == "page" &&      language in [$language, "nl"] &&      slug.current in ["about", "projects", "education", "work", "skills", "contact"]    ] | order(      select(        slug.current == "about" => 0,        slug.current == "work" => 1,        slug.current == "projects" => 2,        slug.current == "education" => 3,        slug.current == "skills" => 4,        slug.current == "contact" => 5,        99      ) asc,      select(language == $language => 0, 1) asc    ) {      _id,      _type,      body,      overview,      title,      "slug": slug.current,    }  }
export type HomePageQueryResult = {
  home: {
    _id: string;
    _type: "home";
    overview: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    title: string | null;
  } | null;
  pages: Array<{
    _id: string;
    _type: "page";
    body: Array<
      | ({
          _key: string;
        } & Timeline)
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          caption?: string;
          alt?: string;
          _type: "image";
          _key: string;
        }
    > | null;
    overview: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    title: string | null;
    slug: string | null;
  }>;
};

// Source: app/[lang]/projects/[slug]/page.tsx
// Variable: projectSlugPageMetadataQuery
// Query: *[      _type == "project" &&      slug.current == $slug &&      language in [$language, "nl"]    ] | order(select(language == $language => 0, 1) asc)[0] {      coverImage,      title,      client,      tags,      "overview": pt::text(overview),    }
export type ProjectSlugPageMetadataQueryResult = {
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  title: string | null;
  client: string | null;
  tags: Array<string> | null;
  overview: string;
} | null;

// Source: app/[lang]/projects/[slug]/page.tsx
// Variable: projectSlugPageQuery
// Query: *[      _type == "project" &&      slug.current == $slug &&      language in [$language, "nl"]    ] | order(select(language == $language => 0, 1) asc)[0] {      _id,      _type,      client,      coverImage,      coverVideoUrl,      description,      duration,      overview,      site,      "slug": slug.current,      tags,      title,    }
export type ProjectSlugPageQueryResult = {
  _id: string;
  _type: "project";
  client: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  coverVideoUrl: string | null;
  description: Array<
    | ({
        _key: string;
      } & Timeline)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  duration: Duration | null;
  overview: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  site: string | null;
  slug: string | null;
  tags: Array<string> | null;
  title: string | null;
} | null;

// Source: app/[lang]/projects/page.tsx
// Variable: projectsPageMetadataQuery
// Query: *[_type == "page" && slug.current == "projects" && language in [$language, "nl"]]      | order(select(language == $language => 0, 1) asc)[0] {      title,      "overview": pt::text(overview),    }
export type ProjectsPageMetadataQueryResult = {
  title: string | null;
  overview: string;
} | null;

// Source: app/[lang]/projects/page.tsx
// Variable: projectsPageQuery
// Query: *[_type == "page" && slug.current == "projects" && language in [$language, "nl"]]      | order(select(language == $language => 0, 1) asc)[0] {      _id,      _type,      overview,      title,    }
export type ProjectsPageQueryResult = {
  _id: string;
  _type: "page";
  overview: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  title: string | null;
} | null;

// Source: app/sitemap.ts
// Variable: sitemapEntriesQuery
// Query: {  "pages": *[_type == "page" && defined(slug.current)]{    "slug": slug.current,    language,    _updatedAt  },  "projects": *[_type == "project" && defined(slug.current)]{    "slug": slug.current,    language,    _updatedAt  }}
export type SitemapEntriesQueryResult = {
  pages: Array<{
    slug: string | null;
    language: "en" | "nl" | null;
    _updatedAt: string;
  }>;
  projects: Array<{
    slug: string | null;
    language: "en" | "nl" | null;
    _updatedAt: string;
  }>;
};

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings" && language in [$language, "nl"]]    | order(select(language == $language => 0, 1) asc)[0]{    _id,    _type,    footer,    language,    menuItems[]{      _key,      ...@->{        _type,        language,        "slug": slug.current,        title      }    },    ogImage,  }
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  footer: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  language: "en" | "nl" | null;
  menuItems: Array<
    | {
        _key: null;
        _type: "home";
        language: "en" | "nl" | null;
        slug: null;
        title: string | null;
      }
    | {
        _key: null;
        _type: "page";
        language: "en" | "nl" | null;
        slug: string | null;
        title: string | null;
      }
    | {
        _key: null;
        _type: "project";
        language: "en" | "nl" | null;
        slug: string | null;
        title: string | null;
      }
  > | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: showcaseProjectsQuery
// Query: *[_type == "home" && language in [$language, "nl"]]    | order(select(language == $language => 0, 1) asc)[0]{    _id,    language,    showcaseProjects[]{      _key,      ...@->{        _id,        _type,        coverImage,        coverVideoUrl,        overview,        "slug": slug.current,        tags,        title,      }    }  }
export type ShowcaseProjectsQueryResult = {
  _id: string;
  language: "en" | "nl" | null;
  showcaseProjects: Array<{
    _key: string;
    _id: string;
    _type: "project";
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    coverVideoUrl: string | null;
    overview: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    slug: string | null;
    tags: Array<string> | null;
    title: string | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: slugsByTypeQuery
// Query: *[    _type == $type &&    language == $language &&    defined(slug.current)  ] {    "slug": coalesce(slug.current, "")  }
export type SlugsByTypeQueryResult = Array<{
  slug: string | "";
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n    *[\n      _type == "page" &&\n      slug.current == $slug &&\n      language in [$language, "nl"]\n    ] | order(select(language == $language => 0, 1) asc)[0] {\n      title,\n      "overview": pt::text(overview),\n    }\n  ': SlugPageMetadataQueryResult;
    '\n    *[\n      _type == "page" &&\n      slug.current == $slug &&\n      language in [$language, "nl"]\n    ] | order(select(language == $language => 0, 1) asc)[0] {\n      _id,\n      _type,\n      body,\n      overview,\n      title,\n      "slug": slug.current,\n    }\n  ': SlugPageQueryResult;
    '{\n    "settings": *[_type == "settings" && language in [$language, "nl"]]\n      | order(select(language == $language => 0, 1) asc)[0]{ogImage},\n    "home": *[_type == "home" && language in [$language, "nl"]]\n      | order(select(language == $language => 0, 1) asc)[0]{\n      title,\n      "overview": pt::text(overview),\n    }\n  }': LayoutMetadataQueryResult;
    '\n  {\n    "home": *[_type == "home" && language in [$language, "nl"]]\n      | order(select(language == $language => 0, 1) asc)[0]{\n      _id,\n      _type,\n      overview,\n      title,\n    },\n    "pages": *[\n      _type == "page" &&\n      language in [$language, "nl"] &&\n      slug.current in ["about", "projects", "education", "work", "skills", "contact"]\n    ] | order(\n      select(\n        slug.current == "about" => 0,\n        slug.current == "work" => 1,\n        slug.current == "projects" => 2,\n        slug.current == "education" => 3,\n        slug.current == "skills" => 4,\n        slug.current == "contact" => 5,\n        99\n      ) asc,\n      select(language == $language => 0, 1) asc\n    ) {\n      _id,\n      _type,\n      body,\n      overview,\n      title,\n      "slug": slug.current,\n    }\n  }\n': HomePageQueryResult;
    '\n    *[\n      _type == "project" &&\n      slug.current == $slug &&\n      language in [$language, "nl"]\n    ] | order(select(language == $language => 0, 1) asc)[0] {\n      coverImage,\n      title,\n      client,\n      tags,\n      "overview": pt::text(overview),\n    }\n  ': ProjectSlugPageMetadataQueryResult;
    '\n    *[\n      _type == "project" &&\n      slug.current == $slug &&\n      language in [$language, "nl"]\n    ] | order(select(language == $language => 0, 1) asc)[0] {\n      _id,\n      _type,\n      client,\n      coverImage,\n      coverVideoUrl,\n      description,\n      duration,\n      overview,\n      site,\n      "slug": slug.current,\n      tags,\n      title,\n    }\n  ': ProjectSlugPageQueryResult;
    '\n    *[_type == "page" && slug.current == "projects" && language in [$language, "nl"]]\n      | order(select(language == $language => 0, 1) asc)[0] {\n      title,\n      "overview": pt::text(overview),\n    }\n  ': ProjectsPageMetadataQueryResult;
    '\n    *[_type == "page" && slug.current == "projects" && language in [$language, "nl"]]\n      | order(select(language == $language => 0, 1) asc)[0] {\n      _id,\n      _type,\n      overview,\n      title,\n    }\n  ': ProjectsPageQueryResult;
    '{\n  "pages": *[_type == "page" && defined(slug.current)]{\n    "slug": slug.current,\n    language,\n    _updatedAt\n  },\n  "projects": *[_type == "project" && defined(slug.current)]{\n    "slug": slug.current,\n    language,\n    _updatedAt\n  }\n}': SitemapEntriesQueryResult;
    '\n  *[_type == "settings" && language in [$language, "nl"]]\n    | order(select(language == $language => 0, 1) asc)[0]{\n    _id,\n    _type,\n    footer,\n    language,\n    menuItems[]{\n      _key,\n      ...@->{\n        _type,\n        language,\n        "slug": slug.current,\n        title\n      }\n    },\n    ogImage,\n  }\n': SettingsQueryResult;
    '\n  *[_type == "home" && language in [$language, "nl"]]\n    | order(select(language == $language => 0, 1) asc)[0]{\n    _id,\n    language,\n    showcaseProjects[]{\n      _key,\n      ...@->{\n        _id,\n        _type,\n        coverImage,\n        coverVideoUrl,\n        overview,\n        "slug": slug.current,\n        tags,\n        title,\n      }\n    }\n  }\n': ShowcaseProjectsQueryResult;
    '\n  *[\n    _type == $type &&\n    language == $language &&\n    defined(slug.current)\n  ] {\n    "slug": coalesce(slug.current, "")\n  }\n': SlugsByTypeQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
